config/routes.rb
Rails.application.routes.draw do
  resources :set_cards do
    resources :flask_cards
  end

  resources :post_comments
  resources :posts 

  resources :hiraganas do
    resources :tests
  end

  devise_for :users
  resources :users
  resources :tests
  resources :stories

  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'homepage#home'
  get 'dict' => 'homepage#dict'
  get 'alphabet' => 'homepage#alphabet'
  get 'stories' => 'stories#index'
  get 'editst' => 'stories#edit'
  get 'songs' => 'homepage#songs'
  get 'infor' => 'users#show'
  delete 'stories/:id' => 'stories#destroy'

end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.admin?
        can :manage, :all
      else
        can [:update, :destroy, :read], [Post]
        can :read, Story
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/flask_card.rb
class FlaskCard < ApplicationRecord
  belongs_to :set_card
end

app/models/hiragana.rb
class Hiragana < ApplicationRecord
    has_many :tests, dependent: :destroy
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_many :post_comment, -> { order "created_at DESC"}
end
# sdasdadasdasdsasdad

app/models/post_comment.rb
class PostComment < ApplicationRecord
    belongs_to :user
end
# dasdsadadadasdsa

app/models/set_card.rb
class SetCard < ApplicationRecord
  belongs_to :user
  has_many :flask_cards, dependent: :destroy
end

app/models/story.rb
class Story < ApplicationRecord
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :hiragana
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :set_cards, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true
  validates :phone, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post_comment = PostComment.new
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:user_id, :post, :created_at)
    end
end

app/controllers/set_cards_controller.rb
class SetCardsController < ApplicationController
  before_action :set_set_card, only: [:show, :edit, :update, :destroy]

  # GET /set_cards
  # GET /set_cards.json
  def index
    @set_cards = SetCard.where(user_id: current_user.id)
  end

  # GET /set_cards/1
  # GET /set_cards/1.json
  def show
  end

  # GET /set_cards/new
  def new
    @set_card = SetCard.new
  end

  # GET /set_cards/1/edit
  def edit
  end

  # POST /set_cards
  # POST /set_cards.json
  def create
    @set_card = SetCard.new(set_card_params)
    @set_card.user_id = current_user.id
    respond_to do |format|
      if @set_card.save
        format.html { redirect_to @set_card, notice: 'Set card was successfully created.' }
        format.json { render :show, status: :created, location: @set_card }
      else
        format.html { render :new }
        format.json { render json: @set_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /set_cards/1
  # PATCH/PUT /set_cards/1.json
  def update
    respond_to do |format|
      if @set_card.update(set_card_params)
        format.html { redirect_to @set_card, notice: 'Set card was successfully updated.' }
        format.json { render :show, status: :ok, location: @set_card }
      else
        format.html { render :edit }
        format.json { render json: @set_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /set_cards/1
  # DELETE /set_cards/1.json
  def destroy
    @set_card.destroy
    respond_to do |format|
      format.html { redirect_to set_cards_url, notice: 'Set card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_set_card
      @set_card = SetCard.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def set_card_params
      params.require(:set_card).permit(:title, :user_id)
    end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
    def index
        @tests = Hiragana.all
    end
    def new
        @test = Test.new
    end
    def create
        @hiragana = Hiragana.find(params[:hiragana_id])
        @test = @hiragana.tests.create(test_params)
        redirect_to hiragana_path(@hiragana)
    end
    def show
        @test = Test.find(params[:id])
        puts @test
    end
    
    private 
        def test_params
            params.require(:test).permit(:question, :answer_a, :answer_b, :answer_c, :answer_d, :correct_answer)
        end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def show
        
    end

    def new
        @user = User.new
    end
    
    def create
        @user = User.new(user_params)
        if @user.save
            #Handle a successful save
            flash[:success] = "Welcome to the H2S!"
            redirect_to @user
        else
            render 'new'
        end
    end
    private
        def user_params
            params.require(:user) .permit(:name, :email, :password, :password_confirmation)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/flask_cards_helper.rb
module FlaskCardsHelper
end

app/helpers/hiraganas_helper.rb
module HiraganasHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/set_cards_helper.rb
module SetCardsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/views/set_cards/_card.html.erb
<div class="col-lg-4 "> 
  <div class="set_card">
    <span class="title">
        <%= set_card.title %>
    </span>
    <div class="trash_icon">
        <%= link_to 'xóa', method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
  </div>
</div>

app/views/set_cards/_form.html.erb
<%= form_with(model: set_card, local: true) do |form| %>
  <% if set_card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(set_card.errors.count, "error") %> prohibited this set_card from being saved:</h2>

      <ul>
        <% set_card.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <label for=""> Tên bộ thẻ: </label>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit :class => "btn btn-primary"%>
  </div>
<% end %>

app/views/set_cards/edit.html.erb
<h1>Editing Set Card</h1>

<%= render 'form', set_card: @set_card %>

<%= link_to 'Show', @set_card %> |
<%= link_to 'Back', set_cards_path %>

app/views/set_cards/index.html.erb
<h1>Flask Card</h1>

<div class="container">
  <h4>
    <%= link_to  new_set_card_path, :action => 'go' do%>
      <button type="button" class="btn btn-primary">Thêm bộ thẻ</button>
    <% end %>
  </h4>
  <div class="row">
    <% @set_cards.each do |set_card| %>
      <%= link_to set_card, :action => 'go' do %>
        <%= render 'card', set_card: set_card %>
      <% end %>
    <% end %>
  </div>
</div>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">

app/views/set_cards/new.html.erb
<div class="container">
    <h1>Tạo bộ thẻ </h1>
    <%= render 'form', set_card: @set_card %>
    <%= link_to 'Back', :back %>
</div>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">

app/views/set_cards/show.html.erb
<div class="container-fluid" style="height:200px">
    <h2><%= @set_card.title %></h2>
    <div class="set_card_container container">
        <div id="myCarousel" class="carousel " data-ride="carousel">
            <div class="flask_cards carousel-inner" role="listbox">
                <% @set_card.flask_cards.each_with_index do |flask_card, index| %>
                    <%= render 'flask_cards/card', flask_card: flask_card, index: index %>
                <% end %>
            </div>
            <div class="prev" href="#myCarousel" role="button" data-slide="prev" >
                <img src="https://img.icons8.com/nolan/96/000000/double-left.png">
            </div>
            <div class="next" href="#myCarousel" role="button" data-slide="next">
                <img src="https://img.icons8.com/nolan/96/000000/double-right.png">
            </div>
        </div>
    <div>
</div>

<%# modal %>

<div class="add container">
    <button type="button" class="btn-lg btn btn-primary" data-toggle="modal" data-target="#myModal">Tạo thẻ mới</button>
    <!-- Modal -->
    <div class="modal fade" id="myModal" role="dialog">
        <div class="modal-dialog">
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Tạo thẻ mới</h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>
                <div class="modal-body">
                    <%= render 'flask_cards/form' %>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
            
        </div>
    </div>
</div>
<%# modal %>

<%# <%= link_to 'Back', set_cards_path %>  
<p class="back-button"><i class="fas fa-backward"></i><%= link_to "Back", set_cards_path %></p>
<p style="margin-bottom: 200px"></p>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
<script >
  $('.carousel').carousel({
    interval: false
  });
</script>